version: '3.8'

services:
  api:
    build: .
    container_name: customer-api
    depends_on:
      - customer-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'
  customer-db:
    image: postgres
    container_name: customer-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'


